#!/usr/bin/env python3

import argparse
import calendar
import datetime
import os
import re
import subprocess
import sys
import tempfile
import warnings

warnings.filterwarnings("ignore", category=UserWarning, module="fs")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONSUMER_SCRIPT = os.path.join(SCRIPT_DIR, "consumer.py")
DEFAULT_LIST = os.getenv("LBS_ANCHORS_FILE", os.path.join(SCRIPT_DIR, "anchors.txt"))
DEFAULT_PACK_PREFIX = "manyclangs/aarch64-ubuntu2004-manyclangs"
HEADER = "# Auto-generated by update_anchors.py. Format: <YYYY-MM> <commit>\n"
SNAPSHOT_RE = re.compile(r"(\d{8})-\d+T(\d{6})-([0-9a-f]+)")


def months_before(dt: datetime.datetime, months: int) -> datetime.datetime:
    month_index = dt.year * 12 + (dt.month - 1) - months
    year, month = divmod(month_index, 12)
    month += 1
    day = min(dt.day, calendar.monthrange(year, month)[1])
    return dt.replace(year=year, month=month, day=day)


def utc_month(timestamp: int) -> str:
    return datetime.datetime.fromtimestamp(timestamp, datetime.timezone.utc).strftime("%Y-%m")


def read_anchors(path: str) -> dict[str, str]:
    anchors = {}
    try:
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) == 2:
                    anchors[parts[0]] = parts[1]
    except FileNotFoundError:
        pass
    return anchors


def write_anchors(path: str, anchors: dict[str, str]) -> None:
    directory = os.path.dirname(path) or "."
    fd, tmp_path = tempfile.mkstemp(
        dir=directory, prefix=".anchors-", suffix=".tmp", text=True
    )
    try:
        with os.fdopen(fd, "w") as f:
            f.write(HEADER)
            for month in sorted(anchors):
                f.write(f"{month} {anchors[month]}\n")
        os.replace(tmp_path, path)
    except BaseException:
        os.unlink(tmp_path)
        raise


def git(*args: str, cwd: str, check: bool = True) -> str:
    res = subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=check,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    return res.stdout.decode().strip()


def resolve_commits(revisions: list[str], llvm_dir: str) -> list[str]:
    if not revisions:
        return []
    res = subprocess.run(
        ["git", "cat-file", "--batch-check=%(objectname) %(objecttype)"],
        cwd=llvm_dir,
        input="\n".join(revisions) + "\n",
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    resolved = []
    for line in res.stdout.splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1] == "commit":
            resolved.append(parts[0])
    return resolved


def commit_timestamps(commits: list[str], llvm_dir: str) -> dict[str, int]:
    if not commits:
        return {}
    res = subprocess.run(
        ["git", "log", "--no-walk", "--format=%H %ct", "--stdin"],
        cwd=llvm_dir,
        input="\n".join(commits) + "\n",
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    timestamps = {}
    for line in res.stdout.splitlines():
        parts = line.split()
        if len(parts) == 2:
            timestamps[parts[0]] = int(parts[1])
    return timestamps


def list_storage_commits(storage_dir: str, binary: str) -> list[str]:
    if not storage_dir:
        return []
    try:
        import fs

        storage = fs.open_fs(storage_dir, writeable=False, create=False)
    except Exception:
        return []
    commits = set()
    prefix = binary + "-"
    try:
        for name in storage.listdir("."):
            if not name.startswith(prefix):
                continue
            commit = name[len(prefix) :].lower()
            if len(commit) == 40 and all(c in "0123456789abcdef" for c in commit):
                commits.add(commit)
    except Exception:
        pass
    return sorted(commits)


def list_snapshots(pack: str, elfshaker: str, manyclangs_local: str) -> list[str]:
    try:
        res = subprocess.run(
            [elfshaker, "list", pack, "--format", "%t"],
            cwd=manyclangs_local,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=120,
        )
    except Exception:
        return []
    if res.returncode != 0:
        return []
    return [line.strip() for line in res.stdout.decode().splitlines() if line.strip()]


def manyclangs_candidates(
    month: str,
    pack_prefix: str,
    elfshaker: str,
    manyclangs_local: str,
    llvm_dir: str,
    max_attempts: int,
) -> list[tuple[int, str]]:
    pack = f"{pack_prefix}-{month.replace('-', '')}"
    snapshots = list_snapshots(pack, elfshaker, manyclangs_local)
    candidates = []
    for snapshot in reversed(snapshots[-max_attempts:]):
        match = SNAPSHOT_RE.match(snapshot)
        if not match:
            continue
        timestamp = int(
            datetime.datetime.strptime(match.group(1) + match.group(2), "%Y%m%d%H%M%S")
            .replace(tzinfo=datetime.timezone.utc)
            .timestamp()
        )
        commit = git("rev-parse", match.group(3), cwd=llvm_dir, check=False)
        if commit:
            candidates.append((timestamp, commit))
    return candidates


def consume(commit: str, binary: str) -> bool:
    with tempfile.TemporaryDirectory(prefix="anchor-") as tmp_dir:
        output = os.path.join(tmp_dir, binary + "-exec")
        try:
            res = subprocess.run(
                [CONSUMER_SCRIPT, commit, binary, output], timeout=180
            )
        except Exception:
            return False
        return res.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Maintain the per-month anchor list used by bisect_service.py. "
        "Candidates come from both the local binary storage and the manyclangs packs, "
        "and a commit is recorded only if consumer.py can produce its binary. "
        "Months already present in the list are skipped, so repeated runs are incremental."
    )
    parser.add_argument("--list", default=DEFAULT_LIST, help="Path to the anchor list file.")
    parser.add_argument(
        "--months",
        type=int,
        default=int(os.getenv("LBS_ANCHOR_MONTHS", "60")),
        help="Number of months to cover.",
    )
    parser.add_argument(
        "--binary",
        default=os.getenv("LBS_ANCHOR_BINARY", "opt"),
        help="Binary to verify with consumer.py.",
    )
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=int(os.getenv("LBS_ANCHOR_MAX_ATTEMPTS", "10")),
        help="Maximum number of candidates to try per month.",
    )
    parser.add_argument(
        "--pack-prefix",
        default=os.getenv("LBS_ANCHOR_PACK_PREFIX", DEFAULT_PACK_PREFIX),
        help="Prefix of the manyclangs pack files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Recompute every month, even if it is already in the list.",
    )
    args = parser.parse_args()

    llvm_dir = os.getenv("LBS_LLVM_REPO")
    if not llvm_dir:
        print("Error: LBS_LLVM_REPO is not set.", file=sys.stderr)
        return 1
    manyclangs_local = os.getenv("LBS_MANYCLANGS_LOCAL")
    elfshaker = os.getenv("LBS_ELFSHAKER_BIN")
    for var, value in [("LBS_MANYCLANGS_LOCAL", manyclangs_local), ("LBS_ELFSHAKER_BIN", elfshaker)]:
        if not value:
            print(f"Error: {var} is not set.", file=sys.stderr)
            return 1
    storage_dir = os.getenv("LBS_STORAGE_DIR", "./storage")

    git("pull", "origin", "main", cwd=llvm_dir)
    bad_commit = git("rev-parse", "origin/main", cwd=llvm_dir)
    bad_time = datetime.datetime.fromtimestamp(
        int(git("show", "-s", "--format=%ct", bad_commit, cwd=llvm_dir)),
        datetime.timezone.utc,
    )

    anchors = read_anchors(args.list)
    for month, commit in list(anchors.items()):
        if not resolve_commits([commit], llvm_dir):
            print(f"Removing stale anchor {month} {commit}")
            del anchors[month]

    missing = []
    for months_back in range(0, args.months + 1):
        month = months_before(bad_time, months_back).strftime("%Y-%m")
        if args.force or month not in anchors:
            missing.append(month)
    if not missing:
        print(f"Nothing to do. {len(anchors)} anchors in {args.list}.")
        return 0

    storage_commits = resolve_commits(list_storage_commits(storage_dir, args.binary), llvm_dir)
    storage_timestamps = commit_timestamps(storage_commits, llvm_dir)
    print(f"Found {len(storage_timestamps)} consumable candidates in local storage.")

    added = 0
    for month in missing:
        candidates = [
            (timestamp, commit)
            for commit, timestamp in storage_timestamps.items()
            if commit != bad_commit and utc_month(timestamp) == month
        ]
        candidates += manyclangs_candidates(
            month, args.pack_prefix, elfshaker, manyclangs_local, llvm_dir, args.max_attempts
        )
        seen = set()
        ordered = []
        for timestamp, commit in sorted(candidates, key=lambda item: item[0], reverse=True):
            if commit not in seen:
                seen.add(commit)
                ordered.append(commit)
        print(f"[{month}] Trying {len(ordered)} candidate(s)...")
        for commit in ordered[: args.max_attempts]:
            if consume(commit, args.binary):
                anchors[month] = commit
                write_anchors(args.list, anchors)
                added += 1
                print(f"[{month}] Anchor: {commit}")
                break
        else:
            print(f"[{month}] No consumable commit found.", file=sys.stderr)

    print(f"Done. {len(anchors)} anchors in {args.list}, {added} added.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
